import 'package:test/test.dart';
import 'package:account_sdk/account_sdk.dart';

// tests for UpdateFCMTokenDTO
void main() {
  final instance = UpdateFCMTokenDTOBuilder();
  // TODO add properties to the builder and call build()

  group(UpdateFCMTokenDTO, () {
    // FCM token for push notifications generated by mobile device.
    // String fcmToken
    test('to test the property `fcmToken`', () async {
      // TODO
    });

  });
}
