name: venille
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.6.5
  dio: ^5.3.3
  intl: ^0.19.0
  path: ^1.9.0
  lottie: ^2.6.0
  app_links: ^6.3.2
  sign_in_with_apple: ^6.1.3
  appcheck: ^1.5.2
  share_plus: ^10.0.3
  dotted_border: ^2.1.0
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.2.0
  get_storage: ^2.1.1
  flutter_svg: ^2.0.7
  flutter_launcher_icons: ^0.11.0
  file_picker: ^5.2.5
  image_picker: ^0.8.7+3
  flutter_image_compress: ^2.0.4
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  visibility_detector: ^0.4.0+2
  google_sign_in: ^6.2.1
  path_provider: ^2.1.0
  lucide_icons: ^0.257.0
  fluentui_system_icons: ^1.1.248
  flutter_animate: ^4.2.0+1
  url_launcher: ^6.1.0
  flutter_upgrade_version: ^1.1.0
  flutter_dotenv: ^5.1.0
  country_picker: ^2.0.17
  flutter_localization: ^0.2.0
  pinput: ^5.0.0
  just_audio: ^0.9.42
  loading_animation_widget: ^1.2.1
  flutter_localizations:
    sdk: flutter
  webview_flutter: ^4.0.5
  socket_io_client: ^2.0.3+1
  flutter_linkify: ^6.0.0
  built_collection: ^5.1.1
  package_info_plus: ^8.1.2
  video_player: ^2.9.2
  permission_handler: ^11.4.0
  auth_sdk:
    path: lib/data/infra_sdk/auth
  account_sdk:
    path: lib/data/infra_sdk/account
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_icons:
    android: true
    ios: true
    image_path: 'assets/logo.jpg'

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/
    - assets/icons/
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
          - asset: assets/fonts/Roboto-Thin.ttf
            weight: 100
          - asset: assets/fonts/Roboto-Light.ttf
            weight: 300
          - asset: assets/fonts/Roboto-Regular.ttf
            weight: 400
          - asset: assets/fonts/Roboto-Medium.ttf
            weight: 500
          - asset: assets/fonts/Roboto-Bold.ttf
    - family: Gotham
      fonts:
          - asset: assets/fonts/Gotham-Bold.otf
          - asset: assets/fonts/Gotham-Black.otf
    - family: Viga
      fonts:
          - asset: assets/fonts/Viga-Regular.ttf
    - family: SourGummy
      fonts:
          - asset: assets/fonts/SourGummy.ttf