// @dart=3.5
//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'update_fcm_token_dto.g.dart';

/// UpdateFCMTokenDTO
///
/// Properties:
/// * [fcmToken] - FCM token for push notifications generated by mobile device.
@BuiltValue()
abstract class UpdateFCMTokenDTO implements Built<UpdateFCMTokenDTO, UpdateFCMTokenDTOBuilder> {
  /// FCM token for push notifications generated by mobile device.
  @BuiltValueField(wireName: r'fcmToken')
  String get fcmToken;

  UpdateFCMTokenDTO._();

  factory UpdateFCMTokenDTO([void updates(UpdateFCMTokenDTOBuilder b)]) = _$UpdateFCMTokenDTO;

  @BuiltValueHook(initializeBuilder: true)
  static void _defaults(UpdateFCMTokenDTOBuilder b) => b;

  @BuiltValueSerializer(custom: true)
  static Serializer<UpdateFCMTokenDTO> get serializer => _$UpdateFCMTokenDTOSerializer();
}

class _$UpdateFCMTokenDTOSerializer implements PrimitiveSerializer<UpdateFCMTokenDTO> {
  @override
  final Iterable<Type> types = const [UpdateFCMTokenDTO, _$UpdateFCMTokenDTO];

  @override
  final String wireName = r'UpdateFCMTokenDTO';

  Iterable<Object?> _serializeProperties(
    Serializers serializers,
    UpdateFCMTokenDTO object, {
    FullType specifiedType = FullType.unspecified,
  }) sync* {
    yield r'fcmToken';
    yield serializers.serialize(
      object.fcmToken,
      specifiedType: const FullType(String),
    );
  }

  @override
  Object serialize(
    Serializers serializers,
    UpdateFCMTokenDTO object, {
    FullType specifiedType = FullType.unspecified,
  }) {
    return _serializeProperties(serializers, object, specifiedType: specifiedType).toList();
  }

  void _deserializeProperties(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
    required List<Object?> serializedList,
    required UpdateFCMTokenDTOBuilder result,
    required List<Object?> unhandled,
  }) {
    for (var i = 0; i < serializedList.length; i += 2) {
      final key = serializedList[i] as String;
      final value = serializedList[i + 1];
      switch (key) {
        case r'fcmToken':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(String),
          ) as String;
          result.fcmToken = valueDes;
          break;
        default:
          unhandled.add(key);
          unhandled.add(value);
          break;
      }
    }
  }

  @override
  UpdateFCMTokenDTO deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final result = UpdateFCMTokenDTOBuilder();
    final serializedList = (serialized as Iterable<Object?>).toList();
    final unhandled = <Object?>[];
    _deserializeProperties(
      serializers,
      serialized,
      specifiedType: specifiedType,
      serializedList: serializedList,
      unhandled: unhandled,
      result: result,
    );
    return result.build();
  }
}

